### ISSUE TITLE
Vim crashes with version c963df1

### ISSUE THREAD

**Issue by felixendres** [Rip-Rip/clang_complete#532]
Lately my clang_complete setup appears to be much less stable. Often the clang library crashes, but sometimes it even kills vim. I installed it via [vim-plug](https://github.com/junegunn/vim-plug), which downloaded version c963df1. Is clang_complete working with libclang 4.0?

Below is the error message with (manual translations of some German). And  below that my vimrc settings.

> Vim: Caught deadly signal SEGV
> Vim: preserving files...
> 
> Error executing "function ClangComplete":Vim: Finished.
> 
> Zeile   22:
> Exception KeyError: KeyError(140211614906112,) in <module 'threading' from '/usr/lib/python2.7/threading.pyc'> ignoredTraceback (most recent call last):
>   File "<string>", line 1, in <module>
>   File "/home/endres/.vim/plugin/libclang.py", line 499, in getCurrentCompletions
>     cancel = int(vim.eval('complete_check()'))
> AttributeError: 'NoneType' object has no attribute 'eval'
> Traceback (most recent call last):
>   File "<string>", line 1, in <module>
> AttributeError: 'NoneType' object has no attribute 'command'
> Traceback (most recent call last):
>   File "<string>", line 1, in <module>
> AttributeError: 'NoneType' object has no attribute 'registerEvent'
> Traceback (most recent call last):
>   File "<string>", line 1, in <module>
> AttributeError: 'NoneType' object has no attribute 'finish'
> 
> clang_complete: completion time 0.023689
> Zeile   50:
> E121: Undefined Variable: l:res
> E15: invalid expression: l:res
> E840: Text deleted by completion function (orig: Text durch Vervollständigungsfunktion gelöscht)
> 

My .vimrc:

> let g:clang_hl_errors=1
> let g:clang_complete_auto = 1
> "let g:clang_library_path="/home/endres/.vim/bundle/YouCompleteMe/third_party/ycmd/libclang.so.3.7"
> let g:clang_use_library=1
> "let g:clang_library_path="/usr/lib/x86_64-linux-gnu/libclang-3.4.so.1"
> let g:clang_library_path="/home/endres/Downloads/clang+llvm-4.0.0-x86_64-linux-gnu-ubuntu-14.04/lib/libclang.so.4.0"
> set completeopt=menu,menuone
> set conceallevel=2
> set concealcursor=vin
> let g:clang_conceal_snippets=1
> let g:clang_snippets=1
> let g:clang_snippets_engine='clang_complete'
> " Limit popup menu height
> set pumheight=20
> let g:clang_complete_copen = 1
> let g:clang_user_options = '-std=c++11 -I./'
> let g:clang_debug=1
> 
> let g:clang_auto_user_options = "compile_commands.json"
> 

I'd appreciate any help, as code completion is quite important for me.

**Comment by xaizek** [comment]
I think it's the same as #446, where wilywampa [speculated](https://github.com/Rip-Rip/clang_complete/issues/446#issuecomment-267509211) that it's due to Vim's python interface. 4.0.0 might have also broken come of the C API, but I don't know if it's the case.

**Comment by felixendres** [comment]
I totally forgot, that I reported this problem already in January in the issue you mentioned. Anyway, I have the feeling that it got worse in the last month or so.
